var a = 2;
a = a - 1;
a++;
var b = 8;
b += 2;
var c = a + b * b;
var d = a * b + b;
var e = a * (b + b);
var f = (a * b) / a;
var g = (b / a) * a;
var nb1 = 3;
nb1 = nb1 - 1;
nb1--;
var nb2 = 8;
nb2 += 2;
var c1 = nb1 + nb2 * nb2;
var d2 = nb1 * nb2 + nb2;
var e2 = nb1 * (nb2 + nb2);
var f2 = (nb1 * nb2) / nb1;
var g2 = (nb2 / nb1) * nb1;
